from datetime import timezone

APP_TIMEZONE = timezone.utc

DEFAULT_PAGE_SIZE = 25
MAX_PAGE_SIZE = 100

DEFAULT_SYNC_PLATFORM = "youtube"
DEFAULT_SYNC_SOURCE = "api"

DEFAULT_METRIC_SNAPSHOT_WINDOW_HOURS = 24

ENGAGEMENT_RATE_PRECISION = 6